In [1]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [4]:
arr = np.ones(4, dtype = np.int64)
# print(arr)

Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [5]:
x = np.array([[2,1],[3,4]])
x = np.matrix(X)

Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [7]:
arr = np.linspace(3.0, 10.0, num=50)
# print(arr)

Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [9]:
x = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.ravel(x)
print(arr)

[1 2 3 4 5 6]


Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [11]:
x = np.arange(1, 10)
arr = np.split(x, [4, 6])
print(arr)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [17]:
x = np.array([[1, 2], [3, 4]])
x_inverse = np.linalg.inv(x)
diagonal_sum = np.trace(x)
print("Inverse of x:")
print(x_inverse)
print("Primary diagonal sum of x:", diagonal_sum)

Inverse of x:
[[-2.   1. ]
 [ 1.5 -0.5]]
Primary diagonal sum of x: 5


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [19]:
x = np.array([[1, 4], [3, 1]])
sorted_x = np.sort(x, axis=1)
print(sorted_x)

[[1 4]
 [1 3]]


Q8 Get the indices that would sort x(as above) along the second axis.

In [21]:
x = np.array([[1, 4], [3, 1]])
sorted_x = np.sort(x, axis=0)
print(sorted_x)

[[1 1]
 [3 4]]


Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [22]:
np.random.seed(42)
x = np.random.uniform(0, 10, (2, 5))

print("x:")
print(x)

max_values = np.amax(x, axis=1)

max_indices = np.argmax(x, axis=1)

min_values = np.amin(x, axis=1)

min_indices = np.argmin(x, axis=1)

print("Maximum values:", max_values)
print("Maximum indices:", max_indices)
print("Minimum values:", min_values)
print("Minimum indices:", min_indices)

x:
[[3.74540119 9.50714306 7.31993942 5.98658484 1.5601864 ]
 [1.5599452  0.58083612 8.66176146 6.01115012 7.08072578]]
Maximum values: [9.50714306 8.66176146]
Maximum indices: [1 2]
Minimum values: [1.5601864  0.58083612]
Minimum indices: [4 1]


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [23]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])



```
# This is formatted as code
```

Drop rows that contain a missing value.

In [26]:
iris_2d = iris_2d[~np.isnan(iris_2d).any(axis=1)]
# print(iris_2d)

Find the correlation between first two columns.

In [27]:
column_1 = iris_2d[:, 0]
column_2 = iris_2d[:, 1]

correlation = np.corrcoef(column_1, column_2)
print(correlation)

[[ 1.         -0.10936925]
 [-0.10936925  1.        ]]


Find the mean,median and standard deviation of column 3.

In [28]:
column_3 = iris_2d[:, 2]

mean = np.mean(column_3)
median = np.median(column_3)
std_dev = np.std(column_3)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)

Mean: 3.758666666666666
Median: 4.35
Standard Deviation: 1.7585291834055212


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [31]:
petal_length = iris_2d[:, 2]
sepal_length = iris_2d[:, 0]

volume = (np.pi * petal_length * (sepal_length ** 2)) / 3
iris_2d = np.column_stack((iris_2d, volume))

Run the following loaad command and solve the following questions

In [37]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Find the count of unique species.

In [38]:
species_column = iris[:, names.index('species')]
unique_species_count = len(np.unique(species_column))
print("Count of unique species:", unique_species_count)

Count of unique species: 3


Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

In [41]:
petal_length = iris[:, names.index('petallength')].astype(float)

text_array = np.where(petal_length < 3, 'small', np.where(petal_length <= 5, 'medium', 'large'))

print(text_array)

['small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small' 'small'
 'small' 'small' 'small' 'small' 'small' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'large' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium'
 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'medium' 'large'
 'large' 'large' 'large' 'large' 'large' 'medium' 'large' 'large' 'large'
 'large' 'large' 'large' 'medium' 'large' 'large' 'large'

Find the most frequent value of petal length (3rd column) in iris dataset

In [42]:
petal_length = iris[:, names.index('petallength')].astype(float)

unique_values, counts = np.unique(petal_length, return_counts=True)
most_frequent_value = unique_values[np.argmax(counts)]

print("Most frequent value of petal length:", most_frequent_value)

Most frequent value of petal length: 1.5
